# generated by datamodel-codegen:
#   filename:  solver.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel
from typing_extensions import TypeAliasType


class DutySolverContract(RootModel[Any]):
    root: Annotated[Any, Field(title='DutySolverContract')]


class Day(RootModel[str]):
    root: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]


class RedDay(RootModel[str]):
    root: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]


class Code(StrEnum):
    D = 'D'
    E = 'E'
    N = 'N'
    S = 'S'
    OFF = 'OFF'
    AL = 'AL'
    LEAVE = 'LEAVE'


class OffKind(StrEnum):
    regular = 'regular'
    sleeping = 'sleeping'
    edu_cont = 'edu_cont'
    edu_union = 'edu_union'
    special = 'special'
    founding = 'founding'


class PrevTailItem(BaseModel):
    userId: str
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    code: Code
    offKind: OffKind | None = None


class NextHeadItem(BaseModel):
    userId: str
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    code: Code
    offKind: OffKind | None = None


class WorkDay(RootModel[str]):
    root: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]


class FixedItem(BaseModel):
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    code: Code
    offKind: OffKind | None = None


class Option(StrEnum):
    OFF = 'OFF'
    D = 'D'
    E = 'E'
    N = 'N'


class Request(BaseModel):
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    options: Annotated[list[Option], Field(min_length=1)]


class NightTarget(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class ShiftCountsBefore(BaseModel):
    D: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    E: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    N: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Nurse(BaseModel):
    id: str
    kTass: bool
    junior: bool
    workDays: list[WorkDay]
    fixed: list[FixedItem]
    requests: list[Request]
    offTarget: float
    nightBankBefore: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    nightMax: Annotated[int, Field(ge=0, le=9007199254740991)]
    nightTarget: NightTarget | None
    weekendMissedStreak: Annotated[int, Field(ge=0, le=9007199254740991)]
    weekendCarryIn: bool
    shiftCountsBefore: ShiftCountsBefore
    balanceShiftTypes: bool
    requestMissBefore: Annotated[int, Field(ge=0, le=9007199254740991)]


class Cell(BaseModel):
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    code: Code
    offKind: OffKind | None = None
    flex: bool | None = None


class Head(BaseModel):
    id: str
    kTass: bool
    junior: bool
    cells: list[Cell]


class Training(BaseModel):
    traineeId: str
    preceptorId: str
    startDate: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    endDate: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    tripleUntil: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    tripleNightsLeft: Annotated[int, Field(ge=0, le=9007199254740991)]


class Rules(BaseModel):
    minStaff: Annotated[int, Field(gt=0, le=9007199254740991)]
    minKTass: Annotated[int, Field(ge=0, le=9007199254740991)]
    minRestHours: Annotated[int, Field(gt=0, le=9007199254740991)]
    maxConsecutiveNight: Annotated[int, Field(gt=0, le=9007199254740991)]
    maxConsecutiveOff: Annotated[int, Field(gt=0, le=9007199254740991)]
    maxConsecutiveWork: Annotated[int | None, Field(gt=0, le=9007199254740991)] = None
    offAfterNight: Annotated[int, Field(ge=0, le=9007199254740991)]
    sleepingOffPerN: Annotated[int, Field(gt=0, le=9007199254740991)]
    forbiddenPatterns: list[str]
    shiftBalanceTolerance: Annotated[int, Field(ge=0, le=9007199254740991)]
    shiftBalanceWindowMonths: Annotated[int, Field(gt=0, le=9007199254740991)]


class Priorities(BaseModel):
    requests: bool
    offAfterNight: bool
    weekendPair: bool
    avoidJuniorOnly: bool
    minimizeRepeatPairs: bool


class SolverRequest(BaseModel):
    contractVersion: Literal[1]
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    timeLimitSec: Annotated[float, Field(gt=0.0, le=60.0)]
    days: Annotated[list[Day], Field(max_length=31, min_length=28)]
    redDays: list[RedDay]
    prevTail: list[PrevTailItem]
    nextHead: list[NextHeadItem] | None = None
    nurses: list[Nurse]
    heads: list[Head]
    trainings: list[Training]
    rules: Rules
    restHours: dict[
        Literal['D', 'E', 'N', 'S'], dict[Literal['D', 'E', 'N', 'S'], float]
    ]
    priorities: Priorities


class Status(StrEnum):
    OPTIMAL = 'OPTIMAL'
    FEASIBLE = 'FEASIBLE'


class Cell1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    userId: str
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]
    code: Code
    offKind: OffKind | None = None


class HeadFillItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    userId: str
    date: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')]


TermsAdditionalProperty = TypeAliasType(
    "TermsAdditionalProperty",
    Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)],
)


class Objective(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    terms: dict[
        Literal[
            'offShortMax',
            'offShort',
            'offOver',
            'requestMissMax',
            'requestMiss',
            'headFill',
            'weekendPair',
            'weekendCarry',
            'workConsec',
            'nightTarget',
            'offAfterNight',
            'sleepingShort',
            'shiftBalance',
            'reverseRotation',
            'juniorOnly',
            'repeatPair',
            'tieBreak',
        ],
        TermsAdditionalProperty,
    ]


class SolverResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    cells: list[Cell1]
    headFill: list[HeadFillItem] | None = None
    objective: Objective
    wallTimeSec: float
    seed: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    solverVersion: str


class Group(StrEnum):
    STAFF = 'STAFF'
    KTASS = 'KTASS'
    NIGHT_MAX = 'NIGHT_MAX'
    NIGHT_CONSEC = 'NIGHT_CONSEC'
    OFF_CONSEC = 'OFF_CONSEC'
    TRAINING = 'TRAINING'
    FIXED = 'FIXED'
    SLEEPING = 'SLEEPING'


class Shift(StrEnum):
    D = 'D'
    E = 'E'
    N = 'N'


class Cause(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: Group
    userId: str | None = None
    date: Annotated[str | None, Field(pattern='^\\d{4}-\\d{2}-\\d{2}$')] = None
    shift: Shift | None = None


class SolverResponse2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['INFEASIBLE']
    causes: list[Cause]
    wallTimeSec: float


class SolverResponse3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['UNKNOWN']
    wallTimeSec: float


class SolverResponse(RootModel[SolverResponse1 | SolverResponse2 | SolverResponse3]):
    root: SolverResponse1 | SolverResponse2 | SolverResponse3
